version: '3.8'
services:
  spark-master:
    image: apache/spark-py
    command: bin/spark-class org.apache.spark.deploy.master.Master
    ports:
      - "7077:7077"  # Spark master port
      - "8080:8080"  # Spark web UI port

  spark-worker:
    image: apache/spark-py
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    depends_on:
      - spark-master
    links:
      - spark-master
    ports:
      - "8081:8081"  # Spark worker web UI port
